version: "3.8"

services:
  replica_1:
    container_name: uptime-kuma-replica-1
    image: realsidsun/replicator-kuma:2.0.0-beta.4-rk1
    hostname: replica-1
    volumes:
      - uptime-kuma-replica-1:/app/data:rw
    ports:
      - "3002:3001"
    environment:
      - REPLICATOR_MODE=RESTORE_LOCAL_ENTITY_REPLICATION # use Local Entity replication - see readme
      - AWS_DEFAULT_REGION=eu-central-1
      - RESTIC_REPOSITORY=s3:s3.amazonaws.com/replicator-kuma
      - AWS_ACCESS_KEY_ID=AKIAJAJSLTZCAZ4SRI5Q
      - AWS_SECRET_ACCESS_KEY=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
      - RESTIC_PASSWORD=I9n7G7G0ZpDWA3GOcJbIuwQCGvGUBkU5
      - NTFY_URL=ntfy.sh/myreplicatorkuma

  replica_2: # only for reference, you should run replicas on different machines (see Readme)
    container_name: uptime-kuma-replica-2
    image: realsidsun/replicator-kuma:2.0.0-beta.4-rk1
    hostname: replica-2
    volumes:
      - uptime-kuma-replica-2:/app/data:rw
    ports:
      - "3002:3001"
    environment:
      - REPLICATOR_MODE=RESTORE
      - AWS_DEFAULT_REGION=eu-central-1
      - RESTIC_REPOSITORY=s3:s3.amazonaws.com/replicator-kuma
      - AWS_ACCESS_KEY_ID=AKIAJAJSLTZCAZ4SRI5Q
      - AWS_SECRET_ACCESS_KEY=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
      - RESTIC_PASSWORD=I9n7G7G0ZpDWA3GOcJbIuwQCGvGUBkU5
      - NTFY_URL=ntfy.sh/myreplicatorkuma

volumes:
  uptime-kuma-replica-1:
  uptime-kuma-replica-2:
