version: '3.8'

services:
  main:
    container_name: uptime-kuma-main
    image: replicator-kuma
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    volumes:
      - uptime-kuma-main:/app/data:rw
    ports:
      - "3001:3001"
    environment:
      - REPLICATOR_MODE=BACKUP
      - AWS_DEFAULT_REGION=eu-central-1
      - RESTIC_REPOSITORY=s3:s3.amazonaws.com/replicator-kuma
      - AWS_ACCESS_KEY_ID=AKIAJAJSLTZCAZ4SRI5Q
      - AWS_SECRET_ACCESS_KEY=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
      - RESTIC_PASSWORD=I9n7G7G0ZpDWA3GOcJbIuwQCGvGUBkU5
  replica:
    container_name: uptime-kuma-replica
    image: replicator-kuma
    volumes:
      - uptime-kuma-replica:/app/data:rw
    ports:
      - "3002:3001"
    environment:
      - REPLICATOR_MODE=RESTORE
      - AWS_DEFAULT_REGION=eu-central-1
      - RESTIC_REPOSITORY=s3:s3.amazonaws.com/replicator-kuma
      - AWS_ACCESS_KEY_ID=AKIAJAJSLTZCAZ4SRI5Q
      - AWS_SECRET_ACCESS_KEY=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
      - RESTIC_PASSWORD=I9n7G7G0ZpDWA3GOcJbIuwQCGvGUBkU5

volumes:
  uptime-kuma-main:
  uptime-kuma-replica:
