name: Docker Image Build and Push CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract Docker base image tag
        id: extract_tag
        run: |
          TAG=$(cat next_tag.txt)
          echo "TAG=$TAG" >> $GITHUB_ENV
          SLIM_TAG=$(cat next_tag_slim.txt)
          echo "SLIM_TAG=$SLIM_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker buildx build --platform linux/amd64,linux/arm64 -t realsidsun/replicator-kuma:$TAG --push -f Dockerfile .
          docker buildx build --platform linux/amd64,linux/arm64 -t realsidsun/replicator-kuma:$SLIM_TAG --push -f slim.Dockerfile .
